/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package portlet.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import portlet.service.model.Factura;
import portlet.service.model.FacturaModel;

/**
 * The base model implementation for the Factura service. Represents a row in the &quot;miEspacio_Factura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>FacturaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FacturaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FacturaImpl
 * @generated
 */
@JSON(strict = true)
public class FacturaModelImpl
	extends BaseModelImpl<Factura> implements FacturaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a factura model instance should use the <code>Factura</code> interface instead.
	 */
	public static final String TABLE_NAME = "miEspacio_Factura";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"facturaId", Types.BIGINT},
		{"numero", Types.VARCHAR}, {"cliente", Types.VARCHAR},
		{"importe", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("facturaId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("numero", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cliente", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("importe", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table miEspacio_Factura (uuid_ VARCHAR(75) null,facturaId LONG not null primary key,numero VARCHAR(75) null,cliente VARCHAR(75) null,importe VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table miEspacio_Factura";

	public static final String ORDER_BY_JPQL =
		" ORDER BY factura.facturaId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY miEspacio_Factura.facturaId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FACTURAID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public FacturaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _facturaId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setFacturaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _facturaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Factura.class;
	}

	@Override
	public String getModelClassName() {
		return Factura.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Factura, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Factura, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Factura, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Factura)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Factura, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Factura, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Factura)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Factura, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Factura, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Factura>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Factura.class.getClassLoader(), Factura.class, ModelWrapper.class);

		try {
			Constructor<Factura> constructor =
				(Constructor<Factura>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Factura, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Factura, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Factura, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Factura, Object>>();
		Map<String, BiConsumer<Factura, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Factura, ?>>();

		attributeGetterFunctions.put("uuid", Factura::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Factura, String>)Factura::setUuid);
		attributeGetterFunctions.put("facturaId", Factura::getFacturaId);
		attributeSetterBiConsumers.put(
			"facturaId", (BiConsumer<Factura, Long>)Factura::setFacturaId);
		attributeGetterFunctions.put("numero", Factura::getNumero);
		attributeSetterBiConsumers.put(
			"numero", (BiConsumer<Factura, String>)Factura::setNumero);
		attributeGetterFunctions.put("cliente", Factura::getCliente);
		attributeSetterBiConsumers.put(
			"cliente", (BiConsumer<Factura, String>)Factura::setCliente);
		attributeGetterFunctions.put("importe", Factura::getImporte);
		attributeSetterBiConsumers.put(
			"importe", (BiConsumer<Factura, String>)Factura::setImporte);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getFacturaId() {
		return _facturaId;
	}

	@Override
	public void setFacturaId(long facturaId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_facturaId = facturaId;
	}

	@JSON
	@Override
	public String getNumero() {
		if (_numero == null) {
			return "";
		}
		else {
			return _numero;
		}
	}

	@Override
	public void setNumero(String numero) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_numero = numero;
	}

	@JSON
	@Override
	public String getCliente() {
		if (_cliente == null) {
			return "";
		}
		else {
			return _cliente;
		}
	}

	@Override
	public void setCliente(String cliente) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cliente = cliente;
	}

	@JSON
	@Override
	public String getImporte() {
		if (_importe == null) {
			return "";
		}
		else {
			return _importe;
		}
	}

	@Override
	public void setImporte(String importe) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_importe = importe;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Factura.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Factura toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Factura>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		FacturaImpl facturaImpl = new FacturaImpl();

		facturaImpl.setUuid(getUuid());
		facturaImpl.setFacturaId(getFacturaId());
		facturaImpl.setNumero(getNumero());
		facturaImpl.setCliente(getCliente());
		facturaImpl.setImporte(getImporte());

		facturaImpl.resetOriginalValues();

		return facturaImpl;
	}

	@Override
	public Factura cloneWithOriginalValues() {
		FacturaImpl facturaImpl = new FacturaImpl();

		facturaImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		facturaImpl.setFacturaId(
			this.<Long>getColumnOriginalValue("facturaId"));
		facturaImpl.setNumero(this.<String>getColumnOriginalValue("numero"));
		facturaImpl.setCliente(this.<String>getColumnOriginalValue("cliente"));
		facturaImpl.setImporte(this.<String>getColumnOriginalValue("importe"));

		return facturaImpl;
	}

	@Override
	public int compareTo(Factura factura) {
		long primaryKey = factura.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Factura)) {
			return false;
		}

		Factura factura = (Factura)object;

		long primaryKey = factura.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Factura> toCacheModel() {
		FacturaCacheModel facturaCacheModel = new FacturaCacheModel();

		facturaCacheModel.uuid = getUuid();

		String uuid = facturaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			facturaCacheModel.uuid = null;
		}

		facturaCacheModel.facturaId = getFacturaId();

		facturaCacheModel.numero = getNumero();

		String numero = facturaCacheModel.numero;

		if ((numero != null) && (numero.length() == 0)) {
			facturaCacheModel.numero = null;
		}

		facturaCacheModel.cliente = getCliente();

		String cliente = facturaCacheModel.cliente;

		if ((cliente != null) && (cliente.length() == 0)) {
			facturaCacheModel.cliente = null;
		}

		facturaCacheModel.importe = getImporte();

		String importe = facturaCacheModel.importe;

		if ((importe != null) && (importe.length() == 0)) {
			facturaCacheModel.importe = null;
		}

		return facturaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Factura, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Factura, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Factura, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Factura)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Factura, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Factura, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Factura, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Factura)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Factura>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _facturaId;
	private String _numero;
	private String _cliente;
	private String _importe;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Factura, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Factura)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("facturaId", _facturaId);
		_columnOriginalValues.put("numero", _numero);
		_columnOriginalValues.put("cliente", _cliente);
		_columnOriginalValues.put("importe", _importe);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("facturaId", 2L);

		columnBitmasks.put("numero", 4L);

		columnBitmasks.put("cliente", 8L);

		columnBitmasks.put("importe", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Factura _escapedModel;

}